import type { DataType } from "@huggingface/transformers";
import type { ConfiguredEmbeddingDevice, EmbeddingConfig, IndexConfig } from "./contracts.ts";
import {
  DEFAULT_EMBEDDING_MODEL_ID,
  EMBEDDING_MODEL_PROFILES,
  embeddingConfigFromProfile,
} from "./embedding-profiles.ts";

export const APPLICATION_NAME = "kbiss";
export const APPLICATION_VERSION = "0.1.0";
export const COMPATIBILITY_DESCRIPTOR_VERSION = 3;
export const DEFAULT_PORT = 3210;
export const DEFAULT_SOURCE_ROOT = "~/dev/card-gateway-artifacts";
/**
 * Root-relative glob rules for generated, dependency, cache, and tool-state content that is rarely
 * useful in a knowledge-base search. A user-supplied `ignorePatterns` array replaces this list.
 * `.git` remains an unconditional discovery invariant even when the configured list is empty.
 */
export const DEFAULT_IGNORE_PATTERNS: readonly string[] = Object.freeze([
  // Dependency trees and local language environments.
  "node_modules/",
  "bower_components/",
  "jspm_packages/",
  ".pnpm-store/",
  ".npm/",
  "**/.yarn/cache/",
  "**/.yarn/unplugged/",
  "vendor/",
  ".venv/",
  "venv/",
  "__pypackages__/",
  "site-packages/",
  ".eggs/",
  "*.egg-info/",
  ".bundle/",
  ".dart_tool/",
  ".pub-cache/",
  ".stack-work/",
  ".cabal-sandbox/",
  ".julia/",
  ".luarocks/",
  "deps/",
  "Pods/",
  "**/Carthage/Build/",
  ".terraform/",
  ".terragrunt-cache/",
  // Generic and language-specific build output.
  "dist/",
  "dist-*/",
  "build/",
  "build-*/",
  "out/",
  "target/",
  "obj/",
  ".build/",
  "DerivedData/",
  ".gradle/",
  "cmake-build-*/",
  "CMakeFiles/",
  "meson-private/",
  "meson-logs/",
  "meson-info/",
  "autom4te.cache/",
  ".deps/",
  ".libs/",
  "bazel-*/",
  "_build/",
  "dist-newstyle/",
  ".bloop/",
  ".metals/",
  ".scala-build/",
  ".kotlin/",
  ".cxx/",
  ".externalNativeBuild/",
  // Framework, compiler, and test output.
  ".next/",
  ".nuxt/",
  ".svelte-kit/",
  ".astro/",
  "**/.angular/cache/",
  ".docusaurus/",
  "storybook-static/",
  ".vite/",
  ".parcel-cache/",
  ".turbo/",
  ".output/",
  ".vercel/",
  ".netlify/",
  ".serverless/",
  ".firebase/",
  ".wrangler/",
  ".sst/",
  ".expo/",
  "coverage/",
  "htmlcov/",
  "cover/",
  ".nyc_output/",
  "test-results/",
  "TestResults/",
  "playwright-report/",
  // Interpreter, linter, and general caches.
  "__pycache__/",
  ".pytest_cache/",
  ".mypy_cache/",
  ".ruff_cache/",
  ".pyre/",
  ".pytype/",
  ".pybuilder/",
  ".tox/",
  ".nox/",
  ".hypothesis/",
  ".ipynb_checkpoints/",
  ".scrapy/",
  ".elixir_ls/",
  ".ruby-lsp/",
  ".phpunit.cache/",
  ".cache/",
  ".tmp/",
  "tmp/",
  "temp/",
  ".history/",
  // Local version-manager installations; selector files such as .nvmrc and .tool-versions remain.
  ".direnv/",
  ".asdf/",
  ".mise/",
  ".rbenv/",
  ".pyenv/",
  ".jenv/",
  ".sdkman/",
  ".volta/",
  ".nodenv/",
  // VCS/editor metadata not covered by the unconditional .git rule.
  ".hg/",
  ".svn/",
  ".bzr/",
  "_darcs/",
  "**/.idea/**/workspace.xml",
  "**/.idea/**/tasks.xml",
  "**/.idea/**/usage.statistics.xml",
  "**/.idea/**/shelf/",
  "**/.idea/**/dataSources/",
  "*.iml",
  "*.suo",
  "*.user",
  "*.userosscache",
  "*.sln.docstates",
  "*.vsix",
  // Compiled artifacts that may appear outside a conventional build directory.
  "*.class",
  "*.jar",
  "*.war",
  "*.ear",
  "*.pyc",
  "*.pyo",
  "*.o",
  "*.obj",
  "*.a",
  "*.lib",
  "*.so",
  "*.so.*",
  "*.dylib",
  "*.dll",
  "*.exe",
  "*.pdb",
  "*.dSYM/",
  "*.app/",
  "*.ipa",
  "*.apk",
  "*.aab",
  "*.aar",
  "*.dex",
  "*.nupkg",
  "*.gem",
  "*.beam",
  "*.ez",
  "*.hi",
  "*.dyn_hi",
  "*.dyn_o",
  "*.cmi",
  "*.cmo",
  "*.cmx",
  "*.cmxa",
  "*.cmxs",
  "*.wasm",
  "*.min.js",
  "*.min.css",
  "*.js.map",
  "*.css.map",
  "*.tsbuildinfo",
  ".eslintcache",
  ".stylelintcache",
  ".ninja_deps",
  ".ninja_log",
  "CMakeCache.txt",
  "cmake_install.cmake",
  ".coverage",
  ".coverage.*",
  "coverage.xml",
  "*.lcov",
  ".phpunit.result.cache",
  ".php-cs-fixer.cache",
  "erl_crash.dump",
  "*.tfstate",
  "*.tfstate.*",
  ".terraform.tfstate.lock.info",
  // Editor backups and interrupted-patch artifacts.
  "*.swp",
  "*.swo",
  "*~",
  "*.bak",
  "*.tmp",
  "*.temp",
  // Temporary filenames containing "temp", matched case-insensitively at any position.
  "*temp*",
  "*temP*",
  "*teMp*",
  "*teMP*",
  "*tEmp*",
  "*tEmP*",
  "*tEMp*",
  "*tEMP*",
  "*Temp*",
  "*TemP*",
  "*TeMp*",
  "*TeMP*",
  "*TEmp*",
  "*TEmP*",
  "*TEMp*",
  "*TEMP*",
  "*.orig",
  "*.rej",
  // Operating-system metadata.
  ".DS_Store",
  ".localized",
  "__MACOSX/",
  ".AppleDouble/",
  "._*",
  "Thumbs.db",
  "Desktop.ini",
]);
export const SUPPORTED_QUANTIZATIONS: ReadonlySet<DataType> = new Set([
  "auto",
  "fp32",
  "fp16",
  "q8",
  "int8",
  "uint8",
  "q4",
  "bnb4",
  "q4f16",
  "q2",
  "q2f16",
  "q1",
  "q1f16",
]);

export const SUPPORTED_EMBEDDING_DEVICES: ReadonlySet<ConfiguredEmbeddingDevice> = new Set([
  "auto",
  "cpu",
  "coreml",
  "webgpu",
]);

/** Concrete compatibility baseline. Runtime configuration selects WebGPU/fp16 on Apple Silicon. */
export const DEFAULT_EMBEDDING_CONFIG = Object.freeze({
  ...embeddingConfigFromProfile(
    EMBEDDING_MODEL_PROFILES[DEFAULT_EMBEDDING_MODEL_ID],
    "cpu",
    "q8",
    384,
  ),
} as const satisfies EmbeddingConfig);

export const DEFAULT_EMBEDDING_DEVICE: ConfiguredEmbeddingDevice = "auto";

export const DEFAULT_INDEX_CONFIG: IndexConfig = Object.freeze({
  chunkOverlapTokens: 50,
  chunkSizeTokens: 400,
  chunkerVersion: 2,
  extractorVersion: 1,
  schemaVersion: 2,
});
